// packages/duck-auth/src/client/solid/types.ts
/** Solid client types — context shape + the public `SolidClient` namespace. */
import type { JSX } from 'solid-js'
import type { Envelope } from '~/core/errors/errors.types'
import type { Identity } from '~/core/identities/identities.types'
import type { VanillaClient } from '../vanilla'

export namespace SolidClient {
  export type Context<Profile extends Identity.ProfileMetadataBase> = {
    client: VanillaClient.Client<Profile>
    state: () => VanillaClient.SessionResult<Profile>
    status: () => 'loading' | 'authed' | 'guest'
    refresh(): Promise<Envelope<VanillaClient.SessionResult<Profile>, string>>
  }

  export interface IProviderProps<Profile extends Identity.ProfileMetadataBase> extends VanillaClient.Config {
    children?: JSX.Element
    /** Pre-built client; overrides config. */
    client?: VanillaClient.Client<Profile>
    /** Disable the initial automatic /session fetch on mount. */
    noInitialFetch?: boolean
  }

  export type UseSessionResult<Profile extends Identity.ProfileMetadataBase> = {
    data: () => VanillaClient.SessionResult<Profile>
    status: () => 'loading' | 'authed' | 'guest'
    refresh(): Promise<Envelope<VanillaClient.SessionResult<Profile>, string>>
  }

  export type MutationResult<I, O> = {
    mutate(input: I): Promise<O>
    loading: () => boolean
    error: () => unknown | null
  }
}

// packages/duck-auth/src/client/react/types.ts
/** React client types - context shape + the public `ReactClient` namespace. */
import type { ReactNode } from 'react'
import type { Envelope } from '~/core/errors/errors.types'
import type { Identity } from '~/core/identities'
import type { VanillaClient } from '../vanilla'

export namespace ReactClient {
  export type ContextValue<Profile extends Identity.ProfileMetadataBase> = {
    client: VanillaClient.Client<Profile>
    state: VanillaClient.SessionResult<Profile>
    status: 'loading' | 'authed' | 'guest'
    refresh(): Promise<Envelope<VanillaClient.SessionResult<Profile>, string>>
  }

  export interface IProviderProps extends VanillaClient.Config {
    children?: ReactNode
    /** Optional pre-built client; overrides cfg. */
    client?: VanillaClient.Client<any>
    /** Disable the initial automatic /session fetch on mount. */
    noInitialFetch?: boolean
  }

  export type UseSessionResult<Profile extends Identity.ProfileMetadataBase> = {
    data: VanillaClient.SessionResult<Profile>
    status: 'loading' | 'authed' | 'guest'
    refresh(): Promise<Envelope<VanillaClient.SessionResult<Profile>, string>>
  }

  export type MutationResult<I, O> = {
    mutate(input: I): Promise<O>
    loading: boolean
    error: unknown | null
  }
}
