// examples/duck-auth/solid/src/form.tsx
import { errorText } from '@examples/duck-auth-ui/api'
import * as ui from '@examples/duck-auth-ui/recipes'
import type { Envelope } from '@gentleduck/auth/client/vanilla'
import { createSignal, type JSX, Show, splitProps } from 'solid-js'

/** A form's submit: hands `send` the fields and the button pressed, and keeps its answer. `null` shows nothing. */
export function createSubmit(send: (form: FormData) => Promise<Envelope<unknown> | null>) {
  const [res, setRes] = createSignal<Envelope<unknown> | null>(null)
  const [pending, setPending] = createSignal(false)

  async function onSubmit(event: SubmitEvent & { currentTarget: HTMLFormElement }) {
    event.preventDefault()
    if (pending()) return
    const form = new FormData(event.currentTarget, event.submitter)
    setPending(true)
    setRes(await send(form))
    setPending(false)
  }

  return { res, pending, onSubmit }
}

export function Field(props: { label: string; name: string } & JSX.InputHTMLAttributes<HTMLInputElement>) {
  const [local, rest] = splitProps(props, ['label'])
  return (
    <div class="grid gap-2">
      <label for={props.name} class={ui.label}>
        {local.label}
      </label>
      <input id={props.name} required class={ui.input} {...rest} />
    </div>
  )
}

/** The last answer: a failure as an alert, a success as `done` when there is one to say. */
export function Notice(props: { res: Envelope<unknown> | null; done?: string; invalid?: string }) {
  const text = () => props.res && (props.res.ok ? props.done : errorText(props.res, props.invalid))
  return (
    <Show when={text()}>
      {(text) => (
        <div role="alert" class={ui.alert({ variant: props.res?.ok ? 'default' : 'destructive' })}>
          <p class={ui.alertDescription}>{text()}</p>
        </div>
      )}
    </Show>
  )
}

// examples/duck-auth/next/src/components/form.tsx
import { errorText } from '@examples/duck-auth-ui/api'
import type { Envelope } from '@gentleduck/auth/client/vanilla'
import { Alert, AlertDescription } from '@gentleduck/registry-ui/alert'
import { Input } from '@gentleduck/registry-ui/input'
import { Label } from '@gentleduck/registry-ui/label'
import { type ComponentProps, type FormEvent, useState } from 'react'

/** A form's submit: hands `send` the fields and the button pressed, and keeps its answer. `null` shows nothing. */
export function useSubmit(send: (form: FormData) => Promise<Envelope<unknown> | null>) {
  const [res, setRes] = useState<Envelope<unknown> | null>(null)
  const [pending, setPending] = useState(false)

  async function onSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()
    if (pending) return
    const { nativeEvent } = event
    const form = new FormData(event.currentTarget, nativeEvent instanceof SubmitEvent ? nativeEvent.submitter : null)
    setPending(true)
    setRes(await send(form))
    setPending(false)
  }

  return { res, pending, onSubmit }
}

export function Field({ label, ...props }: { label: string; name: string } & ComponentProps<'input'>) {
  return (
    <div className="grid gap-2">
      <Label htmlFor={props.name}>{label}</Label>
      <Input id={props.name} required {...props} />
    </div>
  )
}

/** The last answer: a failure as an alert, a success as `done` when there is one to say. */
export function Notice({ res, done, invalid }: { res: Envelope<unknown> | null; done?: string; invalid?: string }) {
  if (!res || (res.ok && !done)) return null
  return (
    <Alert variant={res.ok ? 'default' : 'destructive'}>
      <AlertDescription>{res.ok ? done : errorText(res, invalid)}</AlertDescription>
    </Alert>
  )
}
