// examples/duck-auth/vue/src/pages/ResetPassword.vue
<script setup lang="ts">
import { WEAK_PASSWORD } from '@examples/duck-auth-ui/api'
import * as ui from '@examples/duck-auth-ui/recipes'
import { api } from '../api'
import AuthLayout from '../components/AuthLayout.vue'
import FormField from '../components/FormField.vue'
import FormNotice from '../components/FormNotice.vue'
import { useSubmit } from '../submit'

const token = new URLSearchParams(location.search).get('token') ?? ''
const submit = useSubmit((form) => api.resetPassword(token, String(form.get('password'))))
</script>

<template>
  <AuthLayout title="Choose a new password" description="Every signed-in device is signed out once it changes.">
    <form class="grid gap-4" @submit.prevent="submit.onSubmit">
      <FormField label="New password" name="password" type="password" autocomplete="new-password" />
      <FormNotice :res="submit.res" :invalid="WEAK_PASSWORD" done="Password changed. Sign in with the new one." />
      <button type="submit" :class="ui.button()" :disabled="submit.pending">Change password</button>
    </form>
    <template #footer>
      <a href="/sign-in" class="text-foreground">Back to sign in</a>
    </template>
  </AuthLayout>
</template>

// examples/duck-auth/next/src/app/reset-password/page.tsx
'use client'

import { WEAK_PASSWORD } from '@examples/duck-auth-ui/api'
import { Button } from '@gentleduck/registry-ui/button'
import Link from 'next/link'
import { api } from '@/api'
import { AuthLayout } from '@/components/auth-layout'
import { Field, Notice, useSubmit } from '@/components/form'

export default function ResetPasswordPage() {
  const submit = useSubmit((form) =>
    api.resetPassword(new URLSearchParams(location.search).get('token') ?? '', String(form.get('password'))),
  )

  return (
    <AuthLayout
      title="Choose a new password"
      description="Every signed-in device is signed out once it changes."
      footer={
        <Link href="/sign-in" className="text-foreground">
          Back to sign in
        </Link>
      }>
      <form onSubmit={submit.onSubmit} className="grid gap-4">
        <Field label="New password" name="password" type="password" autoComplete="new-password" />
        <Notice res={submit.res} invalid={WEAK_PASSWORD} done="Password changed. Sign in with the new one." />
        <Button type="submit" loading={submit.pending}>
          Change password
        </Button>
      </form>
    </AuthLayout>
  )
}
